### PR TITLE
Fix CI, update to PySTAC v1

### PR DESCRIPTION
**Pull request by gadomski**
Includes one hackey solution to get validation working by adding items to a dummy collection before validating.

### CODE REVIEW

**Review by lossyrob — APPROVED** [review]
Added commit 97f0149 to simplify the collection setting. Otherwise LGTM

**Comment by lossyrob** [comment]
It's strange that this passed locally through docker/test and not through CI. I think this has to do with source mounting issues. Will fix.

**Comment by lossyrob** [comment]
@gadomski 1d1e8db is the fix for volume mounting that I've seen across the repos; uses `/opt/src` which has since changed.

**Comment by gadomski** [comment]
Roger yeah we'll need to propagate that back up to the template too.

**Pull request merged**
