### PR TITLE
chore: update version from 0.2.0 to 0.2.1

### PR DESCRIPTION
**Pull request by pjhartzell**
Before you submit a pull request, please fill in the following:

**Related Issue(s):**
Please add links (if any) to related github issues.

**Description:**
Please explain the changes you made here.

**PR checklist:**

- [x] Code is formatted (run `scripts/format`).
- [x] Code lints properly (run `scripts/lint`).
- [x] Tests pass (run `scripts/test`).
- [N/A] Documentation has been updated to reflect changes, if applicable.
- [x] Changes are added to the [CHANGELOG](../CHANGELOG.md).
- [N/A] Examples are added to `examples/`

### CODE REVIEW

**Review by gadomski — COMMENTED** [review]
I tried to publish to test PyPI and got the following:

```
$ python -m twine upload --repository testpypi dist/*
Uploading distributions to https://test.pypi.org/legacy/
Uploading stactools_landsat-0.2.1-py3-none-any.whl
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 42.2k/42.2k [00:00<00:00, 77.0kB/s]
Error during upload. Retry with the --verbose option for more details.
HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
Invalid value for requires_dist. Error: Can't have direct dependency: 'stactools @ git+https://github.com/stac-utils/stactools@f31524f03308df94b4836c92abb779f194e34567'
```

Looks like we'll have to wait to release until https://github.com/stac-utils/stactools/pull/259 is merged (and probably released).

**Comment by pjhartzell** [comment]
Ah. Inconvenient, but not end of world.

**Comment by gadomski** [comment]
@pjhartzell you could now update to stactools v0.3.0 and we could get this PR merged.

**Review by gadomski — APPROVED** [review]
`scripts/publish --test` ran a-ok so looks good to go.

**Pull request merged**
